# Generated by Django 2.0.13 on 2019-08-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('code', models.SlugField(max_length=15, verbose_name='Código')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descrição')),
                ('part_number', models.SlugField(blank=True, null=True, verbose_name='part_number')),
                ('datasheet', models.URLField()),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'Itens',
                'ordering': ['name'],
            },
        ),
    ]
