# Generated by Django 2.0.13 on 2019-08-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroitens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='datasheet',
            field=models.URLField(blank=True, null=True),
        ),
    ]
